FROM bacbia/zero2prod:latest as builder

FROM ubuntu
WORKDIR /app
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends openssl ca-certificates \
  # Clean up
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*
COPY configuration configuration
ENV APP_ENVIRONMENT production
ENTRYPOINT [ "/bin/bash" ]
