# -------------------------------------------------
GET http://localhost:8000/health_check
# -------------------------------------------------
GET https://zero2prod-k5bl8.ondigitalocean.app/health_check


# -------------------------------------------------
POST http://localhost:8000/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin&email=ursula_le_guin%40gmail.com
# -------------------------------------------------
POST https://zero2prod-k5bl8.ondigitalocean.app/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin&email=ursula_le_guin%40gmail.com


# -------------------------------------------------
POST http://localhost:8000/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin


# -------------------------------------------------
# Send email
POST https://api.sendgrid.com/v3/mail/send
Host: api.sendgrid.com
Authorization: Bearer {{SENDGRID_TOKEN}}
Content-Type: application/json

{
  "personalizations": [
    {
      "to": [
        {
          "email": "bacbia3696@gmail.com"
        }
      ]
    }
  ],
  "from": {
    "email": "bacbia3696@gmail.com"
  },
  "subject": "Sending with SendGrid is Fun",
  "content": [
    {
      "type": "text/plain",
      "value": "and easy to do anywhere, even with cURL"
    },
    {
      "type": "text/html",
      "value": "<html><body><strong>Hello</strong> dear Postmark user.</body></html>"
    }
  ]
}
